### PR TITLE
Adding nutrients components #14

### PR DESCRIPTION
**Pull request by mattjbr123**
Nutrient components added to the tests and main code. Main changes to framework code are in component and model.py. Changes made are documented in issues #14 and #93.
Let's see if the tests pass...

### CODE REVIEW

**Comment by mattjbr123** [comment]
Let's see what I overlooked... 😅

**Comment by mattjbr123** [comment]
Missing dummy data file dummy_subsurface_parameter_d_pt5deg.nc in tests/data

**Comment by mattjbr123** [comment]
Just some of the doc tests that are failing now

**Comment by mattjbr123** [comment]
@rich-HJ @ThibHlln could you review this before I merge the changes into main? Given it's such a big change it'd be nice to have a second and third pair of eyes in case I missed anything...

**Comment by ThibHlln** [comment]
Hi Matt. Apologies but on my side I won't have enough time to review this. :-/

**Comment by mattjbr123** [comment]
No problem Thibault, I understand! It is a lot to look through... @rich-HJ will appreciate whatever you can give!

**Comment by mattjbr123** [comment]
@ThibHlln I've merged the changes into main now, how did you then push it to pypi/conda?

**Pull request merged**
